server:
  port: 1101
spring:
  application:
    name: command
  main.allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
      url: jdbc:h2:mem:~/jpa;DB_CLOSE_ON_EXIT=FALSE
hack.lmax:
  enable: true
  bufferSize: 2048
  handlerSize: 10
